db:
  host: '127.0.0.1'
  user: 'root'
  pass: 'root'
  database: 'test'
  #database: 'crawler'

app:
  threads: 5
  word_limit: 100000
  retry_limit: 3

server:
  qihu:
    host: 'www.so.com'
    port: 80
  baidu:
    host: 'www.baidu.com'
    port: 80
